import { AnimalCategory, Location, Theme } from './types'

export const animalCategories: AnimalCategory[] = [
  {
    id: 'mar',
    emoji: '🌊',
    namePt: 'Animais do Mar',
    nameCa: 'Animals del Mar',
    animals: [
      { id: 'golfinho', emoji: '🐬', namePt: 'Golfinho', nameCa: 'Dofí' },
      { id: 'tubarao', emoji: '🦈', namePt: 'Tubarão', nameCa: 'Tauró' },
      { id: 'polvo', emoji: '🐙', namePt: 'Polvo', nameCa: 'Pop' },
      { id: 'tartaruga', emoji: '🐢', namePt: 'Tartaruga', nameCa: 'Tortuga' },
      { id: 'baleia', emoji: '🐳', namePt: 'Baleia', nameCa: 'Balena' },
      { id: 'estrela', emoji: '⭐', namePt: 'Estrela do Mar', nameCa: 'Estrella de Mar' },
      { id: 'peixe', emoji: '🐠', namePt: 'Peixe Palhaço', nameCa: 'Peix Pallasso' },
      { id: 'cavalo-marinho', emoji: '🌿', namePt: 'Cavalo Marinho', nameCa: 'Cavallet de Mar' },
    ],
  },
  {
    id: 'dinossauros',
    emoji: '🦕',
    namePt: 'Dinossauros',
    nameCa: 'Dinosaures',
    animals: [
      { id: 'trex', emoji: '🦖', namePt: 'T-Rex', nameCa: 'T-Rex' },
      { id: 'triceratops', emoji: '🦕', namePt: 'Triceratops', nameCa: 'Triceratops' },
      { id: 'pterossauro', emoji: '🦅', namePt: 'Pterossauro', nameCa: 'Pterosaure' },
      { id: 'estegossauro', emoji: '🦴', namePt: 'Estegossauro', nameCa: 'Estegosaure' },
      { id: 'braquiossauro', emoji: '🌿', namePt: 'Braquiossauro', nameCa: 'Braquiosaure' },
      { id: 'ankilossauro', emoji: '🛡️', namePt: 'Ankilossauro', nameCa: 'Ankilosaure' },
    ],
  },
  {
    id: 'floresta',
    emoji: '🌲',
    namePt: 'Floresta',
    nameCa: 'Bosc',
    animals: [
      { id: 'urso', emoji: '🐻', namePt: 'Urso', nameCa: 'Ós' },
      { id: 'raposa', emoji: '🦊', namePt: 'Raposa', nameCa: 'Guineu' },
      { id: 'coruja', emoji: '🦉', namePt: 'Coruja', nameCa: 'Mussol' },
      { id: 'esquilo', emoji: '🐿️', namePt: 'Esquilo', nameCa: 'Esquirol' },
      { id: 'cervo', emoji: '🦌', namePt: 'Cervo', nameCa: 'Cérvol' },
      { id: 'lobo', emoji: '🐺', namePt: 'Lobo', nameCa: 'Llop' },
      { id: 'coelho', emoji: '🐇', namePt: 'Coelho', nameCa: 'Conill' },
      { id: 'ourico', emoji: '🦔', namePt: 'Ouriço', nameCa: 'Eriçó' },
    ],
  },
  {
    id: 'fazenda',
    emoji: '🐄',
    namePt: 'Fazenda',
    nameCa: 'Granja',
    animals: [
      { id: 'vaca', emoji: '🐄', namePt: 'Vaca', nameCa: 'Vaca' },
      { id: 'cavalo', emoji: '🐴', namePt: 'Cavalo', nameCa: 'Cavall' },
      { id: 'galinha', emoji: '🐔', namePt: 'Galinha', nameCa: 'Gallina' },
      { id: 'porco', emoji: '🐷', namePt: 'Porco', nameCa: 'Porc' },
      { id: 'ovelha', emoji: '🐑', namePt: 'Ovelha', nameCa: 'Ovella' },
      { id: 'pato', emoji: '🦆', namePt: 'Pato', nameCa: 'Ànec' },
      { id: 'gato', emoji: '🐱', namePt: 'Gato', nameCa: 'Gat' },
      { id: 'cao', emoji: '🐶', namePt: 'Cão', nameCa: 'Gos' },
    ],
  },
  {
    id: 'safari',
    emoji: '🦁',
    namePt: 'Safari',
    nameCa: 'Safari',
    animals: [
      { id: 'leao', emoji: '🦁', namePt: 'Leão', nameCa: 'Lleó' },
      { id: 'elefante', emoji: '🐘', namePt: 'Elefante', nameCa: 'Elefant' },
      { id: 'girafa', emoji: '🦒', namePt: 'Girafa', nameCa: 'Girafa' },
      { id: 'zebra', emoji: '🦓', namePt: 'Zebra', nameCa: 'Zebra' },
      { id: 'hipopotamo', emoji: '🦛', namePt: 'Hipopótamo', nameCa: 'Hipopotam' },
      { id: 'macaco', emoji: '🐵', namePt: 'Macaco', nameCa: 'Mico' },
      { id: 'rinoceronte', emoji: '🦏', namePt: 'Rinoceronte', nameCa: 'Rinoceront' },
      { id: 'leopardo', emoji: '🐆', namePt: 'Leopardo', nameCa: 'Lleopard' },
    ],
  },
  {
    id: 'jardim',
    emoji: '🌸',
    namePt: 'Jardim',
    nameCa: 'Jardí',
    animals: [
      { id: 'borboleta', emoji: '🦋', namePt: 'Borboleta', nameCa: 'Papallona' },
      { id: 'abelha', emoji: '🐝', namePt: 'Abelha', nameCa: 'Abella' },
      { id: 'joaninha', emoji: '🐞', namePt: 'Joaninha', nameCa: 'Marieta' },
      { id: 'caracol', emoji: '🐌', namePt: 'Caracol', nameCa: 'Cargol' },
      { id: 'passaro', emoji: '🐦', namePt: 'Pássaro', nameCa: 'Ocell' },
      { id: 'lagarta', emoji: '🐛', namePt: 'Lagarta', nameCa: 'Eruga' },
    ],
  },
]

export const locations: Location[] = [
  { id: 'floresta', emoji: '🌲', namePt: 'Floresta Encantada', nameCa: 'Bosc Encantat' },
  { id: 'mar', emoji: '🌊', namePt: 'Fundo do Mar', nameCa: 'Fons del Mar' },
  { id: 'castelo', emoji: '🏰', namePt: 'Castelo Mágico', nameCa: 'Castell Màgic' },
  { id: 'escola', emoji: '🏫', namePt: 'Escola', nameCa: 'Escola' },
  { id: 'espaco', emoji: '🚀', namePt: 'Espaço', nameCa: 'Espai' },
  { id: 'dinossauros', emoji: '🌋', namePt: 'Mundo dos Dinossauros', nameCa: 'Món dels Dinosaures' },
  { id: 'montanha', emoji: '🏔️', namePt: 'Montanha Mágica', nameCa: 'Muntanya Màgica' },
  { id: 'jardim', emoji: '🌸', namePt: 'Jardim Secreto', nameCa: 'Jardí Secret' },
  { id: 'caverna', emoji: '🕌', namePt: 'Caverna das Maravilhas', nameCa: 'Cova de les Meravelles' },
  { id: 'nuvens', emoji: '☁️', namePt: 'Reino das Nuvens', nameCa: 'Regne dels Núvols' },
]

export const themes: Theme[] = [
  {
    id: 'emocoes',
    emoji: '💛',
    namePt: 'Controlar Emoções',
    nameCa: 'Controlar Emocions',
    descPt: 'Aprender a reconhecer e lidar com sentimentos',
    descCa: 'Aprendre a reconèixer i gestionar els sentiments',
  },
  {
    id: 'sensorial',
    emoji: '🌟',
    namePt: 'Sensibilidade Sensorial',
    nameCa: 'Sensibilitat Sensorial',
    descPt: 'Lidar com sons, texturas e luzes fortes',
    descCa: 'Gestionar sons, textures i llums fortes',
  },
  {
    id: 'brinquedos',
    emoji: '🧸',
    namePt: 'Guardar Brinquedos',
    nameCa: 'Guardar Joguines',
    descPt: 'A importância de organizar e cuidar dos brinquedos',
    descCa: "La importància d'organitzar i cuidar les joguines",
  },
  {
    id: 'higiene',
    emoji: '🚿',
    namePt: 'Higiene Pessoal',
    nameCa: 'Higiene Personal',
    descPt: 'Banho, escovar dentes e se cuidar',
    descCa: "Dutxa, rentar les dents i cuidar-se",
  },
  {
    id: 'voz',
    emoji: '🔊',
    namePt: 'Falar em Voz Baixa',
    nameCa: 'Parlar en Veu Baixa',
    descPt: 'Aprender quando e como modular o volume da voz',
    descCa: 'Aprendre quan i com modular el volum de la veu',
  },
  {
    id: 'gestos',
    emoji: '🤲',
    namePt: 'Calma no Corpo',
    nameCa: 'Calma al Cos',
    descPt: 'Reconhecer gestos repetitivos e encontrar calma',
    descCa: 'Reconèixer gestos repetitius i trobar calma',
  },
  {
    id: 'amigos',
    emoji: '🤝',
    namePt: 'Fazer Amigos',
    nameCa: 'Fer Amics',
    descPt: 'Como brincar e se relacionar com outras crianças',
    descCa: 'Com jugar i relacionar-se amb altres nens',
  },
  {
    id: 'comer',
    emoji: '🍽️',
    namePt: 'Hora de Comer',
    nameCa: 'Hora de Menjar',
    descPt: 'Experimentar novos alimentos e sentar à mesa',
    descCa: 'Experimentar nous aliments i seure a taula',
  },
  {
    id: 'dormir',
    emoji: '🌙',
    namePt: 'Hora de Dormir',
    nameCa: 'Hora de Dormir',
    descPt: 'A rotina da noite e a importância do descanso',
    descCa: 'La rutina de nit i la importància del descans',
  },
]
